sudo: requried
services:
  - docker

before_install:
  - docker build -t shashil05chitra/docker-react -f Dockerfile.dev .

script:
  - docker run shashil05chitra/docker-react npm run test -- --coverage
 
