version: '3'
services:
  reactappweb:
    build: 
      context: .
      dockerfile: Dockerfile.dev          
    ports:
      - "3000:3000"
    volumes:
     # - "$PWD/node_modules:/sh/app"
      - /app/node_modules
      - .:/sh/app
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/sh/app
    command: ["npm", "run", "test"] 

